### PR TITLE
Remove time 0.1 dependency

### PR DESCRIPTION
**Pull request by msrd0**

### CODE REVIEW

**Comment by msrd0** [comment]
CI seems to fail on macOS only with some error message I've never seen before. Not sure if that's my fault, or what to do to make CI happy.

**Comment by tshepang** [comment]
I would bump msrv until finding one that does not fail CI, and starting with edition 2021 (Rust 1.56), because why not

**Comment by msrd0** [comment]
Looks like it works with 1.56 ([CI](https://github.com/msrd0/next-rust-release-date/actions/runs/6048951507)). I also updated some actions you use to get rid of the github deprecation warning regarding node 12. The only one I couldn't find a newer version of is `actions-rs/audit-check`.

**Comment by tshepang** [comment]
I see 0.4.19 already had time dep optional, where `clock` feature was enough. But will accept this anyway, and do some other changes, then a release.

**Pull request merged**
